version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bookstore-postgres
    environment:
      POSTGRES_DB: bookstoredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qtl
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: bookstore-app
    ports:
      - "8082:8081"
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstoredb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qtl

volumes:
  pgdata:

networks:
  backend:
